# Generated by Django 4.2.5 on 2023-09-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_type', models.CharField(max_length=1000, null=True)),
                ('inv_description', models.TextField(max_length=1000, null=True)),
                ('inv_property', models.TextField(max_length=1000, null=True)),
                ('inv_model', models.TextField(max_length=1000, null=True)),
                ('inv_serial', models.TextField(max_length=1000, null=True)),
                ('inv_acqDate', models.CharField(max_length=1000, null=True)),
                ('inv_acqCost', models.CharField(max_length=1000, null=True)),
                ('inv_accountable', models.IntegerField(null=True)),
                ('inv_loc', models.CharField(max_length=1000, null=True)),
                ('inv_class', models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'inventories',
            },
        ),
    ]
