# Generated by Django 4.2.5 on 2023-09-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySupplyApp', '0002_alter_inventory_inv_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inv_acqCost',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inv_acqDate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inv_class',
            field=models.CharField(choices=[('Motor Vehicles', 'Motor Vehicles'), ('Aircraft and Aircrafe Ground Equipment', 'Aircraft and Aircrafe Ground Equipment'), ('Other Transportation Equipment', 'Other Transportation Equipment'), ('Disaster Response and Rescue Equipment', 'Disaster Response and Rescue Equipment'), ('Land', 'Land'), ('Other Land Improvements', 'Other Land Improvements'), ('Sewer Systems', 'Sewer Systems'), ('Power Supply Systems', 'Power Supply Systems'), ('Airport Systems', 'Airport Systems'), ('Airport Equipment', 'Airport Equipment'), ('Buildings', 'Buildings'), ('Other Structures', 'Other Structures'), ('Office Equipment', 'Office Equipment'), ('Furniture & Fixtures', 'Furniture & Fixtures'), ('Other Property Plant and Equipment', 'Other Property Plant and Equipment'), ('Information and Communication Technical Equipment', 'Information and Communication Technical Equipment'), ('Communication Equipment', 'Communication Equipment'), ('Medical Equipment', 'Medical Equipment'), ('Technical and Scientific Equipment', 'Technical and Scientific Equipment'), ('Other Equipment', 'Other Equipment')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inv_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inv_loc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inv_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inv_property',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inv_serial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inv_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
