# Generated by Django 4.2.4 on 2023-09-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySupplyApp', '0004_alter_inventory_inv_acqcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inv_type',
            field=models.CharField(choices=[('Semi-expendable Equipment', 'Semi-expendable Equipment'), ('Non-expended Equipment', 'Non-expended Equipment')], max_length=100, null=True),
        ),
    ]
