# Generated by Django 4.2.4 on 2023-09-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySupplyApp', '0005_alter_inventory_inv_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inv_description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
