# Generated by Django 4.2.4 on 2023-09-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySupplyApp', '0006_alter_inventory_inv_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inv_description',
            field=models.TextField(max_length=2147483647, null=True),
        ),
    ]
