# Generated by Django 4.2.4 on 2023-09-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySupplyApp', '0007_alter_inventory_inv_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inv_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
