# Generated by Django 4.2.4 on 2023-09-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySupplyApp', '0008_inventory_inv_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inv_accPerson',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inv_status',
            field=models.CharField(choices=[('Available-Service', 'Available-Service'), ('Unavailable-Service', 'Unavailable-Service')], max_length=100, null=True),
        ),
    ]
