# Generated by Django 4.2.4 on 2023-09-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySupplyApp', '0009_inventory_inv_accperson_inventory_inv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inv_accountable',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
