# Generated by Django 4.2.4 on 2023-09-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySupplyApp', '0010_alter_inventory_inv_accountable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inv_accPerson',
        ),
    ]
